language: node_js
node_js:
  - "7.4"

branches:
  only:
    - master

before_script:
  - git config --global user.name "TravisCI"
  - git config --global user.email "travisCI@nekomy.com"
  - npm install -g firebase-tools

script:
  - npm install
  - npm run build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
