language: node_js
node_js:
  - "4.5"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm version patch

script:
  - npm run build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}