language: node_js
node_js:
  - "4.5"

branches:
  only:
    - master

before_script:
  - git config --global user.name "TravisCI"
  - git config --global user.email "travisCI@theon.io"
  - npm install -g firebase-tools

script:
  - npm install
  - npm run build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}